version: '3.4'

services:
  estadomaterias:
    image: estadomaterias
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000